### ISSUE TITLE
Implement REST2

### ISSUE THREAD

**Issue by alberto99** [maccallumlab/meld#6]
Efficient use of REMD with explicit solvent.

**Comment by alberto99** [comment]
Should we consider also trying Carlos' hybrid implicit/explicit solvent approach? Would have to setup the system twice to generate implicit solvent radii.

**Comment by jlmaccal** [comment]
I'm not sure how that approach works (link?), but it sounds complicated. For now, I'd like to keep it simple.

**Comment by jlmaccal** [comment]
I've assigned this to myself, as I have some ideas for how to do this.

I think the best strategy is to use `ParmEd` to modify the topology to change the epsilon values of the proteins and to scale the dihedrals.

However, I might hold off a bit. The code to actually build the openmm system and add all of the forces is a pretty huge mess. I think it would be good to have "system transformers" that take a system and modify in certain ways: add forces, scale parameters, etc. Then the `OpenMMRunner` only needs to keep a list of transformations to apply.

**Comment by lvotapka** [comment]
Looking more into how to do this, I found that OpenMM Force objects can have their parameters changed directly from the Python wrapper. For example:

sys = simulation.system
nbs = sys.getForce(3)\
for particle_id in range(nbs.getNumParticles()):
  oldparam = nbs.getParticleParameters(particle_id)
  oldparam[0] *= 0.01 # scaling charges
  oldparam[2] *= 0.01 # scaling epsilons
  nbs.setParticleParameters(particle_id, *oldparam)


I know this is a little hard-codey, but I think that I can put something similar directly into the OpenMMRunner class to modify the simulation parameters at the start of each REMD simulation based on the temperature_scaler value for that particular alpha (then, of course, set the temperature of the replicas all to be the same). 

Justin if you have a sample setup.py script for an explicit system, would you upload that here? That would be very helpful.

**Comment by jlmaccal** [comment]
Overall, I would be very much against just hacking this into the OpenMMRunner class. There are a number of reasons for this.

The biggest reason is that this approach just doesn't scale. We already have tons of hard to read code for SC interactions and the various forces. Continuing down this path will just make this work. I know it would be easiest to just hack it in, but we're better off in the long run if we do it "right". I think moving to some type of system transformer class is the way to go. We just need to figure out the right API. After that, it should be very easy to implement REST this way. I will also move all of the existing crap code that adds MELD forces to use this new system.

Second, it's not just as simple as scaling the LJ parameters and charges. We'll also want to scale torsions. How are you going to find all of the correct parameters to change? For example, you don't want to change water, or to change torsions that keep rings flat. So there's going to be a fair amount of logic in deciding which parameters to change. Also, the value of alpha can change during the simulation do to adaptation of the REMD ladder, so you need to store all of the original parameters in order to adapt when alpha changes. This is way to much functionality to stick into the OpenMMRunner without making it very complex and hard to maintain, given all of the other things it has to do. As I said above, we will be much better off if we have classes specifically tasked with modifying the system in certain ways.

**Comment by lvotapka** [comment]
I understand your reluctance to implement a "hack" in those classes. Would you be more specific about what you mean by "transformer"? I'm not familiar with that term. If you have a link or a paper that talks about it, I'd be interested to learn more about it. Is it something similar to OpenMM's "CustomManyParticle" force?

Whatever it is, it would need to be able to not only modify the MELD restrain parameters, but also the normal MD forcefield parameters as a function of alpha (and other variables, like whether the parameter is "solute" or "solvent). 

To answer your question about how I was going to change the parameters of the torsions, I was considering, as a first pass, to just modify the parameters of ALL the proper torsions, assuming that waters and dissolved ions wouldn't have any proper torsions. Otherwise, I would simply code up some sort of logic to go through each of the torsions & particles, see which part of the system they comprise, and determine whether they are solute or solvent, and modify the parameters as needed. As for when alpha would change as it moved up and down the replica ladder, I would scale back to the scale parameters based on the ratio of the old alpha to the new alpha. At least, these were the things I was planning to do.

Would you be willing to be more specific about how this will be accomplished, and what role I should play in it? Alternatively, if you'd prefer to implement all this yourself, just let me know and I can sit tight while you're doing it.

Also, please send me a setup.py script for an explicit solvent system in MELD at your earliest convenience.

**Comment by jlmaccal** [comment]
@lvotapka Sorry, I was traveling all last week.

I've started implementing this on the transformers branch. Have a look at `transform.py`. For REST, I think it will work something like this:
- `__init__` will simply store the parameters related to REST
- `add_interactions` will do nothing
- `finalize` will store the indices and starting non-bonded parameters for all non-solvent molecules. It will also store the indices and starting parameters for all non-solvent, non-improper dihedrals. Working out how to do the indexing is the only tricky part, but the openmm topology object should have all the information we need.
- `update` will scale the non bonded and torsion parameters that were saved, based on the current value of alpha.

I think this should be pretty easy to implement, so I can probably bang this out by next week if things go well. My plan is to first convert over all of the existing gross code in the openmm runner to use this new transformer idea, then I'll add REST2 support.

I will pass along a script for explicit solvent next time I'm in my office. Basically, you have to manually setup the system using leap, and then load the top and crd files directly into MELD. After that, you just set a few options to tell it not to use gb, to use a periodic box with pressure coupling, etc.

**Comment by jlmaccal** [comment]
Sorry, I forgot to send the script for explicit solvent. I'll do it tomorrow.

Now that I've implemented the transformer system, it should be very easy to implement REST2. I should have this done tomorrow.

The only challenging part is identifying the dihedrals that should not be perturbed, like impropers.

**Comment by lvotapka** [comment]
Hi Justin, no rush on the explicit solvent script. I'm very interested to see the transformers class that you're working on.

As for the improper dihedrals, the paper made it seem like all of the forcefield energy parameters that apply to the solutes can be scaled. Though they mentioned that in practice, they don't scale the bond and angle energies. They didn't mention the impropers. So as a first pass, you might be able to just modify the improper torsions the same way that you modify the proper torsions, making no distinction between them.

**Comment by jlmaccal** [comment]
>  I'm very interested to see the transformers class that you're working on.

They are in the transformers branch. Check in `meld.system.openmm_runner.transform`.

> As for the improper dihedrals, the paper made it seem like all of the forcefield energy parameters that apply to the solutes can be scaled. Though they mentioned that in practice, they don't scale the bond and angle energies. They didn't mention the impropers. So as a first pass, you might be able to just modify the improper torsions the same way that you modify the proper torsions, making no distinction between them.

Good point. As a first pass, I'll just do all dihedrals. However, I think it's worth not perturbing torsions that are intended to keep groups planar. Allowing these groups to be more flexible doesn't help with conformational sampling, rather it just makes exchanges harder.

**Comment by jlmaccal** [comment]
@lvotapka OK, I think this is working now. Check out the transformers branch and see if it works for you.

You can see an example script for both explicit solvent and rest2 here:
https://gist.github.com/jlmaccal/9be711029e9f9ffeb2b8e9b9dc93c853

Note, that you have to manually build the explicit solvent systems using amber's tools. One strategy is to run for a while using implicit solvent and then extract one of the frames to input into tleap in order to build an explicit system.

Also note that many of the restraints are likely to fail with periodic systems. They will probably work for restraints within a molecule, but will give strange behavior between molecules.

**Comment by jlmaccal** [comment]
I spoke to someone who has worked with REST before, and apparently it's critical that we do not scale the impropers meant to either maintain stereo chemistry or keep the peptide bond planar. Without this, we will end up with chiral inversions and cis-trans isomerization of peptides.

**Comment by lvotapka** [comment]
OK, I think this is working now. Check out the transformers branch and see if it works for you.
Yes, I see that you've implemented it, very cool! I'll check out your setup scripts over the next few days.

Also note that many of the restraints are likely to fail with periodic systems. They will probably work for restraints within a molecule, but will give strange behavior between molecules.
I'll keep this in mind.

I spoke to someone who has worked with REST before, and apparently it's critical that we do not scale the impropers meant to either maintain stereo chemistry or keep the peptide bond planar. Without this, we will end up with chiral inversions and cis-trans isomerization of peptides.
Ok that makes sense.

**Comment by alberto99** [comment]
@jlmaccal ,
I've been running the first test sets on trp-cage for testing the REST2 implementation. I have not scaled to high effective temperatures for fear of the inversion, but   it looks like not scaling the improper dihedrals could be done easily. 
https://github.com/ParmEd/ParmEd/pull/555/files
Jason put an omm_dihedral_force in parmed that allows to split which dihedrals are improper and which proper. So they could be just excluded from the list of modified dihedrals.
I'm not sure what is the most efficient way to pass the parm object or the topology/restart to the transformer to do that step though. What do you think?

**Comment by jlmaccal** [comment]
@alberto99 good catch!

I'm not quite sure of the best way to use this either, but I'll look into it. One worry I have is that if we give `ParmEd` the same topology string as `OpenMM`, I'm not sure if it's guaranteed that all of the torsions, etc are in the same order. But we could probably do something like this:

1. Pass the topology string to the `__init__` function of the REST transformer.
2. Use parmed to identify all of the impropers and note their indices.
3. Double check that the corresponding dihedrals from the OpenMM simulation involve the same atoms.
4. Skip over all of the impropers when doing REST.

Alternatively, we could try to identify how ParmEd identifies the impropers and just re-use that logic in MELD.

**Comment by jlmaccal** [comment]
We figured out how to identify the impropers, so they should be handled correctly now.
