### ISSUE TITLE
Communication with mpi protocols

### ISSUE THREAD

**Issue by alberto99** [maccallumlab/meld#75]
@jlmaccal , thank you for your help wiht the python3.7. That helped a lot and helped move things forward on this end. 
We have had issues with openmpi and slurm when changing from a pmix_V1 protocol to v2 and v3. 

The issue has been associated with 
Error: UCP worker does not support MPI_THREAD_MULTIPLE

This can be fixed by adding 
import mpi4py.rc
mpi4py.rc.threads = False

right before calling from mpi4py import MPI in comm.py

Doing this i'm able to run with 
  1) python/3.8   2) cuda/10.0.130   3) gcc/9.3.0   4) openmpi/3.1.2   5) cmake/3.15.6   6) swig/3.0.8   7) doxygen/1.8.3.1   8) netcdf/4.2

on our local cluster. I'm not sure if this is an issue with the different openmpi compilations here (we have tried several combinations of openmpi python and gcc) or if it is a larger thing.

If you think this is useful i can push the changes to comm.py

**Comment by frank-stonybrook** [comment]
My guess is that it relates to whether the openmpi module has been compiled with multi-threads support. I am curious about what happens if you run something like this on a compute node
```python
from mpi4py import MPI
print(MPI.Query_thread())
```

If you get something like 2, it means that your underly openmpi library doesn't support multi-threads.  My wild guess is that the timeout context manager in **comm.py** relies on some form of multi-threading mechanism which throw the error you saw before. 

On the laufer cluster, the underlying openmpi library supports multi-thread (MPI.Query_thread() call output 3) and we don't need  
```python
import mpi4py.rc
mpi4py.rc.threads = False
````
to make things work.

**Comment by jlmaccal** [comment]
The timeout code doesn’t use threading at all. Instead it relies on signal handling. The `threading` library is imported, but only to make sure that only the main (and in our case, only) thread is setting the signal handler 

@alberto99 your fix looks reasonable. Is there any way to test it on a couple of clusters?

**Comment by frank-stonybrook** [comment]
Okay. But I am still wondering whether the MPI library on Al's cluster has been compiled properly with multi-thread support. I am currently running simulations on Frontera and Summit, but should be able to test it in a day or two once they are done. I have a feeling that we don't need this trick to make things work in properly configured environment. Is there any consequence of turning off multi-threads support while we might need them somewhere else in the program?

**Comment by alberto99** [comment]
I was playing around with this more and though this might be better, where
it allows one to decide what we want. As Justin said, we only have one main
thread, so i don't see that having multiple threads enabled is necessary. I
can reproduce failures once i set the thread level to multiple. And yes,
this is due to incompatibilities with the openmpi compiled in the system.

import mpi4py.rc

mpi4py.rc.threads = True

#mpi4py.rc.thread_level = 'funneled'

#mpi4py.rc.thread_level = 'multiple'

#mpi4py.rc.thread_level = 'single'

mpi4py.rc.thread_level = 'serialized'

**Comment by jlmaccal** [comment]
@frank-stonybrook I don't fully understand what is going on. I don't think this is a problem with MELD per se. It is likely an MPI  / queuing system configuration issue, but I don't really know how to debug things.

I don't see any harm in the proposed changes, at least for the CUDA implementation of MELD, as we don't use threads anywhere. But this could be a problem if we get a CPU implementation.

**Comment by jlmaccal** [comment]
> And yes, this is due to incompatibilities with the openmpi compiled in the system.

We should try to understand what is causing the underlying issue. I don't really understand the finer points of how MPI works with threads, or why @alberto99's install, in particular, is causing problems.

**Comment by alberto99** [comment]
Agreed, this is not a MELD problem. That's why i opened a separate ticket
from the python3.7 compatibility.

This is just something i have hit myself in a wall in the past week and
thought might be helpful.

**Comment by alberto99** [comment]
Agreed, i will continue working with our sys. adm. to find out more about
the multiple thread issues on our cluster.

**Comment by jlmaccal** [comment]
> This is just something i have hit myself in a wall in the past week and thought might be helpful.

It would be great for us to figure out how to sort this out. MPI is a common problem spot for users, as there are so many different MPI implementations, often compiled for specific interconnects. None of it is that well supported, and it's often hard to google for things since it is so specialized.

From what I can gather:
- mpi4py is by default asking for `multiple` thread level, which allows for multiple threads to each interact with the `mpi` library.
- In MELD, only the main python thread ever interacts with MPI, so even if we used threads in the OpenMM kernels, this shouldn't cause any problems as they are not making MPI calls.

Based on that, I think requesting something other than `multiple` is likely to work, but we should do a bit more digging to make sure my understanding is correct.

**Comment by frank-stonybrook** [comment]
> @frank-stonybrook I don't fully understand what is going on. I don't think this is a problem with MELD per se. It is likely an MPI / queuing system configuration issue, but I don't really know how to debug things.
> 
> I don't see any harm in the proposed changes, at least for the CUDA implementation of MELD, as we don't use threads anywhere. But this could be a problem if we get a CPU implementation.

Sorry for the confusion. Yes, the StopIterator issue is one thing, this one is another. I am totally agree it has nothing to do with MELD. 

> Based on that, I think requesting something other than multiple is likely to work, but we should do a bit more digging to make sure my understanding is correct.

Agree! I am suspecting that the OpenMPI library which mpi4py module relies on in Al's cluster might not properly compiled with multi-thread enabled. Getting the compilation flags of the OpenMPI library from the system admin should be able to tell whether that's the cause.  

Let me know what I can help!

**Comment by frank-stonybrook** [comment]
A quick update @alberto99. You can figure out whether your MPI library support multi-threads by trying this command
`ompi_info | grep -i thread`

Here is the output from Laufer cluster which use OpenMPI
`Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
   FT Checkpoint support: no (checkpoint thread: no)`

If you don't see **MPI_THREAD_MULTIPLE: yes**, it means that your underly MPI library doesn't compiled with multi-threads feature enabled which could lead to the error you saw before. 
Then You can recompile OpenMPI with multi-heard enabled: 
`./configure --enable-mpi-thread-multiple`

Source: https://stackoverflow.com/questions/36563438/mpi-with-multiple-pthreads

**Comment by alberto99** [comment]
Thanks Cong,
ompi_info | grep -i thread
          Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support:
yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
   FT Checkpoint support: no (checkpoint thread: no)

I believe this is an issue between the openmpi and slurm -- and as Justin
said, there is not that much to find on the web. Recently our slurm system
was updated to  SLURM 17.11.7. And as a result the protocol mpix_v1 was
discontinued. Mpix_v2 and mpix_v3 are the ones that are in place now.

There have been multiple variables changing at once, so it has been hard to
pinpoint the problem -- but it seems like it is getting closer.
Al.

**Comment by frank-stonybrook** [comment]
Thanks, Al! Yea, it at least confirmed that your OpenMPI library properly compiled with multi-thread enabled. Another simple test just to rule out maybe some default settings in your environment:

- What's the output of `echo $SLURM_CPUS_PER_TASK` if you add it before your mpirun command in the slurm job script?
  This variable controls the default threads allowed for the submitted job. I am wondering maybe your slurm scheduler     preset it to one to lower cpu loads.  

- What happens if you add `#SBATCH --cpus-per-task=3` in your slurm job script? According to the slurm document, it should allow up to 3 threads/CPUs per MPI task.

**Comment by ca-taylor** [comment]
> Okay. But I am still wondering whether the MPI library on Al's cluster has been compiled properly with multi-thread support. I am currently running simulations on Frontera and Summit, but should be able to test it in a day or two once they are done. I have a feeling that we don't need this trick to make things work in properly configured environment. Is there any consequence of turning off multi-threads support while we might need them somewhere else in the program?

Yes. All of our MPI builds have multi-threading enabled.   The problem is not with OpenMPI but with UCX where multiple thread support (MPI_THREAD_MULTIPLE) is not supported by default.   The openib BTL has been deprecated in OpenMPI in favor of the UCX communication layer.  

> Recently our slurm system was updated to SLURM 17.11.7. And as a result the protocol mpix_v1 was discontinued. Mpix_v2 and mpix_v3 are the ones that are in place now. There have been multiple variables changing at once, so it has been hard to pinpoint the problem -- but it seems like it is getting closer. Al.

SLURM was upgraded from 19.05 to 20.02.  At that time, we dropped support for PMIx_v1 but kept PMIx_v2 and PMIx_v3.   The PMIx version required is determined at the time that OpenMPI is built and, unfortunately, only one version is supported per build.   

We have OpenMPI builds available from OpenMPI 3.0.0 (pmix_v1) to OpenMPI 4.0.4 (pmix_v3).   We are trying to move Alberto forward to a newer OpenMPI/PMIx combination but have run into many hurdles most of which have been overcome.  However, I'm currently hitting what looks like a Python 3.8/SWIG when building OpenMMSwigHeaders.i.  I'll open a separate issue for that.

**Comment by frank-stonybrook** [comment]
> Yes. All of our MPI builds have multi-threading enabled. The problem is not with OpenMPI but with UCX where multiple thread support (MPI_THREAD_MULTIPLE) is not supported by default. The openib BTL has been deprecated in OpenMPI in favor of the UCX communication layer.

Good to know that!  In the past, we use either well-established supercomputing facility or not aggressive updated in-house computing platform. So we have been largely immune from those low layer library issues.

**Comment by alberto99** [comment]
Have not heard more issues from this, so closing the issue.
